name: Update gist with WakaTime stats
on:
  schedule:
    - cron: "0 0 * * *"
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Update gist
        uses: matchai/waka-box@master
        env:
          GH_TOKEN: 0a93d23424c63d5605fbb9bad39beec35b7fbca0
          GIST_ID: aa987fea7ee37296be552aa6bbbcc5ff
          WAKATIME_API_KEY: 9c0c1223-c86d-4141-b0b9-b34a3bf51bc3
